name: PR build test

on:
  pull_request_target:

jobs:
  build:
    uses: ndechesne/meta-qcom-test/.github/workflows/premerge-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 initramfs-test-image initramfs-test-full-image initramfs-firmware-image initramfs-rootfs-image cryptodev-module
      machines: >-
        ['dragonboard-410c', 'dragonboard-845c', 'qrb5165-rb5', 'qcom-armv8a', 'sdx55-mtp', 'sa8155p-adp', 'qcom-armv7a']
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      branch: ${{github.base_ref}}
      url: ${{github.server_url}}/${{github.repository}}
    secrets: inherit
