on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      images:
        required: true
        type: string
      distro:
        required: true
        type: string
      machines:
        required: true
        type: string
    secrets:
      TUXSUITE_TOKEN:
        required: true

env:
  POKY_URL: http://git.yoctoproject.org/git/poky

jobs:
  meta-qcom-premerge-build-test:
    name: ${{ matrix.machine }}/${{ matrix.tclibc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine: ${{inputs.machines}}
        tclibc: [glibc, musl]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade tuxsuite
    - name: Setup tux definition
      env:
        MACHINE: ${{ matrix.machine }}
        TCLIBC: ${{ matrix.tclibc }}
        PR: ${{ github.event.pull_request.number }}
        IMAGES: ${{inputs.images}}
        DISTRO: ${{inputs.distro}}
        HOST: ${{inputs.host}}
      run: |
        cat << EOF > tux.json
        {
          "sources": {
            "git_trees": [
              {
                "url": "$POKY_URL",
                "branch": "$GITHUB_BASE_REF"
              },
              {
                "url": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY",
                "ref": "refs/pull/$PR/merge"
              }
            ]
          },
          "container": "$HOST",
          "envsetup": "poky/oe-init-build-env",
          "distro": "$DISTRO",
          "machine": "$MACHINE",
          "target": "$IMAGES",
          "bblayers_conf": [
            "BBLAYERS += '../meta-qcom/'"
          ],
          "artifacts": [
            "\$DEPLOY_DIR"
          ],
            "environment": {
          },
          "local_conf": [
            "INHERIT += 'buildstats buildstats-summary'",
            "TCLIBC := '$TCLIBC'"
          ]
        }
        EOF
    - name: Run build
      run: |
        cat tux.json
        echo tuxsuite bake submit tux.json
      env:
        TUXSUITE_TOKEN: ${{ secrets.TUXSUITE_TOKEN }}
