name: PR build test

on:
  pull_request_target:

jobs:
  build:
    uses: ndechesne/meta-qcom-test/.github/workflows/premerge-template.yml@master
    with:
      distro: poky
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 initramfs-test-image initramfs-test-full-image cryptodev-module
      machines: >-
        ['dragonboard-410c', 'dragonboard-845c', 'qrb5165-rb5', 'qcom-armv8a', 'sa8155p-adp']
    secrets: inherit
